--creation de l'utilisateur
CFREATE USER CSI3

IDENTIFIED BY CSI3 ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO CSI3;

GRANT ALL PRIVILEGES TO CSI3;

CONNECT CSI3/CSI3;

--connect sys AS sysdba

--connect SYS/SYS$2022 AS SYSDBA;

SET VERIFY OFF

SET LINESIZE 900

SET PAGESIZE 100

--chemin run pour creation des table

@./TABLES/ADRESSE

@./TABLES/ANNONCES

@./TABLES/ATTRIBUT

@./TABLES/BESOIN_CLIENT

@./TABLES/CLIENTS

@./TABLES/OFFRE

@./TABLES/PERSONNES

@./TABLES/PRESSING

@./TABLES/PRIVILEGE

@./TABLES/PROMO

@./TABLES/RESSOURCES_PHYSIQUES

@./TABLES/ROLES

@./TABLES/SERVICES

@./TABLES/TYPE_LINGE

@./TABLES/TYPE_SERVICE

@./TABLES/UTILISATEUR

@./TABLES/VALEUR_ATTRIBUT

--chemin run pour creation des contrainte

@./CONTRAINT/ADRESSE_CONTRAINT

@./CONTRAINT/ANNONCES_CONTRAINT

@./CONTRAINT/ATTRIBUT_CONTRAINT

@./CONTRAINT/BESOIN_CLIENT_CONTRAINT

@./CONTRAINT/CLIENTS_CONTRAINT

@./CONTRAINT/OFFRE_CONTRAINT

@./CONTRAINT/PERSONNES_CONTRAINT

@./CONTRAINT/PRESSING_CONTRAINT

@./CONTRAINT/PRIVILEGE_CONTRAINT

@./CONTRAINT/PROMO_CONTRAINT

@./CONTRAINT/RESOURCE_CONTRAINT

@./CONTRAINT/ROLES_CONTRAINT

@./CONTRAINT/SERVICES_CONTRAINT

@./CONTRAINT/TYPE_LINGE_CONTRAINT

@./CONTRAINT/TYPE_SERVICE_CONTRAINT

@./CONTRAINT/UTILISATEUR_CONTRAINT

@./CONTRAINT/VALEUR_ATTRIBUT_CONTRAINT