--SET PAGESIZE 100;

SET LINESIZE 500;

SET VERIFY OFF;

SET ECHO OFF;

/*
PROMPT ############### CREATION BASE DE DONNEES DE L'APPLICATION PRESSINGS ############################';

ACCEPT MOT_PASSE PROMPT 'ENTREZ LE MOT DE PASSE DE LA BASE DE DONNEES' HIDE;

--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER CSI3 IDENTIFIED BY &MOT_PASSE;

GRANT ALL PRIVILEGES TO CSI3;

CONNECT CSI3/&MOT_PASSE@LOCALHOST:1521/XEPDB1;
*/
--CONNECT CSI3/csi3@LOCALHOST:1521/XEPDB1;

PROMPT ###################### CRÉATION DES TABLES ###################################################

@./TABLES/ADRESSE

@./TABLES/ANNONCES

@./TABLES/BESOIN_CLIENT

@./TABLES/CLIENTS

@./TABLES/OFFRE

@./TABLES/PRESSING

@./TABLES/PRIVILEGE

@./TABLES/PROMO

@./TABLES/ROLES

@./TABLES/SERVICES

@./TABLES/TYPE_LINGE

@./TABLES/TYPE_SERVICE

@./TABLES/UTILISATEUR

@./TABLES/PRIVILEGE_ROLES

@./TABLES/PRIVILEGE_UTILISATEUR

@./TABLES/ROLES_UTILISATEUR

PROMPT ###################### CRÉATION DES CONTRAINTES ###################################################

@./CONTRAINT/PRESSING_CONTRAINT

@./CONTRAINT/ROLES_CONTRAINT

@./CONTRAINT/UTILISATEUR_CONTRAINT

@./CONTRAINT/TYPE_SERVICE_CONTRAINT

@./CONTRAINT/SERVICES_CONTRAINT

@./CONTRAINT/TYPE_LINGE_CONTRAINT

@./CONTRAINT/ROLES_UTILISATEUR_CONTRAINT

@./CONTRAINT/ADRESSE_CONTRAINT

@./CONTRAINT/ANNONCES_CONTRAINT

@./CONTRAINT/CLIENTS_CONTRAINT

@./CONTRAINT/BESOIN_CLIENT_CONTRAINT

@./CONTRAINT/OFFRE_CONTRAINT

@./CONTRAINT/PRIVILEGE_CONTRAINT

@./CONTRAINT/PROMO_CONTRAINT

@./CONTRAINT/PRIVILEGE_ROLES_CONTRAINT

@./CONTRAINT/PRIVILEGE_UTILISATEUR_CONTRAINT