CREATE OR REPLACE FUNCTION CREATION_UTILISATEUR(
    MOT_PASSE VARCHAR2
) RETURN CHAR AS
    CREATION_USER_ERROR EXCEPTION;
    PRAGMA EXCEPTION_INIT(CREATION_USER_ERROR, -01920);
BEGIN
    EXECUTE IMMEDIATE '';
    DBMS_OUTPUT.PUT_LINE('TML');
    RETURN '1';
EXCEPTION
    WHEN CREATION_USER_ERROR THEN
        RETURN '0';
END;
/