/*GRANT ALL PRIVILEGES TO SYSTEM;

--SELECT sys_context('USERENV', 'CURRENT_USER') FROM dual;
SELECT
    *
FROM
    ALL_USERS;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
*/

--create user csi3 IDENTIFIED by csi3;
SELECT
    *
FROM
    ALL_USERS;

--CONNECT csi3/csi3@LOCALHOST:1521/XEPDB1;

--GRANT ALL PRIVILEGES TO CSI3;
--DEFINE A=&A;

--ACCEPT V PROMPT 'Entrez mot de passe ' HIDE;

--PRINT V;
--DROP USER CSI3;

--CONNECT CSI3/csi3@LOCALHOST:1521/XEPDB1;