CREATE TABLE `BESOIN_CLIENT` (
  `ID_BESOIN_CLIENT` INT(10) NOT NULL,
  `NOM_BESOIN_CLIENT` VARCHAR(255) NOT NULL,
  `DESCRIPTION_BESOIN_CLIENT` VARCHAR(255) NOT NULL,
  `ID_UTILISATEUR` INT(10) NOT NULL,
  `ID_TYPE_LINGE` INT(10) NOT NULL,
  `ID_ADRESSE` INT(10) NOT NULL,
  `ID_CLIENT` INT(10) NOT NULL
);