CREATE TABLE CLIENTS (
  ID_CLIENT NUMBER(10) NOT NULL,
  NOM_CLIENT VARCHAR2(255) NOT NULL,
  TELEPHONE_CLIENT NUMBER(10) NOT NULL
);

COMMENT ON TABLE CLIENTS IS 'Les potentiels clients de agences de pressing.';