CREATE TABLE OFFRE (
  ID_OFFRE NUMBER(10) NOT NULL,
  ID_SERVICE NUMBER(10) NOT NULL,
  ID_TYPE_LINGE NUMBER(10) NOT NULL,
  DESCRIPTION_OFFRE VARCHAR2(255) NOT NULL,
  PRIX NUMBER(10) NOT NULL,
  QUANTITE NUMBER(10) NOT NULL
);

COMMENT ON TABLE OFFRE IS 'Les offres du pressings.';