CREATE TABLE `OFFRE` (
  `ID_OFFRE` INT(10) NOT NULL,
  `ID_SERVICE` INT(10) NOT NULL,
  `ID_TYPE_LINGE` INT(10) NOT NULL,
  `DESCRIPTION_OFFRE` VARCHAR(255) NOT NULL,
  `PRIX` INT(10) NOT NULL,
  `QUANTITE` INT(10) NOT NULL
);