CREATE TABLE PRESSING (
  ID_PRESSING NUMBER(10) NOT NULL,
  NOM_PRESSING VARCHAR2(255) NOT NULL,
  LOCALISATION VARCHAR2(255) NOT NULL
);

COMMENT ON TABLE PRESSING IS 'Table qui contient les informations du pressing créé.';