CREATE TABLE PRIVILEGE (
  ID_PRIVILEGE NUMBER(10) NOT NULL,
  NOM_PRIVILEGE VARCHAR2(255) NOT NULL,
  ID_UTILISATEUR NUMBER(10) NOT NULL,
  ID_ROLE NUMBER(10) NOT NULL
);

COMMENT ON table PRIVILEGE IS 'table qui contient les privilèges des utilisateurs.';