CREATE TABLE `PROMO` (
  `ID_SERVICE` INT(10) NOT NULL,
  `ID_TYPE_LINGE` INT(10) NOT NULL,
  `ID_PROMO` INT(10) NOT NULL,
  `DURE_PROMO` INT(10) NOT NULL,
  `DESCRIPTION_PROMO` VARCHAR(255) NOT NULL
);