CREATE TABLE PROMO (
  ID_SERVICE NUMBER(10) NOT NULL,
  ID_TYPE_LINGE NUMBER(10) NOT NULL,
  ID_PROMO NUMBER(10) NOT NULL,
  DURE_PROMO NUMBER(10) NOT NULL,
  DESCRIPTION_PROMO VARCHAR2(255) NOT NULL
);

COMMENT ON TABLE PROMO IS 'Les promotions des articles';