CREATE TABLE SERVICES (
  ID_SERVICE NUMBER(10) NOT NULL,
  NOM_SERVICE VARCHAR2(255) NOT NULL,
  DESCRIPTION_SERVICE VARCHAR2(255) NOT NULL,
  ID_PRESSING NUMBER(10) NOT NULL,
  ID_TYPE_SERVICE NUMBER(10)
);

COMMENT ON TABLE SERVICES IS 'Les services du pressing';