CREATE TABLE UTILISATEUR (
  NOM_UTILISATEUR VARCHAR2(30) NOT NULL UNIQUE,
  MOT_PASSE VARCHAR(50) NOT NULL,
  NOM VARCHAR2(30) NOT NULL,
  PRENOM VARCHAR2(30) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  ID_PRESSING NUMBER(10) UNIQUE,
  ID_UTILISATEUR NUMBER(10) NOT NULL
);

COMMENT ON TABLE UTILISATEUR IS 'Les utilisateurs de la plateforme, les clients et/ou les responsable de pressings';