CREATE TABLE `UTILISATEUR` (
  `NOM_UTILISATEUR` VARCHAR(10) NOT NULL,
  `PRENOM_UTILISATEUR` VARCHAR(255) NOT NULL,
  `ADRESS_UTILISATEUR` VARCHAR(255) NOT NULL,
  `ID_PRESSING` INT(10) NOT NULL,
  `ID_UTILISATEUR` INT(10) NOT NULL
);