CREATE TABLE UTILISATEUR (
  NOM_UTILISATEUR VARCHAR2(10) NOT NULL,
  PRENOM_UTILISATEUR VARCHAR2(255) NOT NULL,
  ADRESS_UTILISATEUR VARCHAR2(255) NOT NULL,
  ID_PRESSING NUMBER(10) UNIQUE,
  ID_UTILISATEUR NUMBER(10) NOT NULL
);

COMMENT ON TABLE UTILISATEUR IS 'Les utilisateurs de la plateforme, les clients et/ou les responsable de pressings';