CREATE TABLE `VALEUR_ATTRIBUT` (
  `ID_SERVICE` INT(10) NOT NULL,
  `ID_TYPE_LINGE` INT(10) NOT NULL,
  `ID_VALEUR_ATTRIBUT` INT(10) NOT NULL,
  `NOM_VALEUR_ATTRIBUT` VARCHAR(255) NOT NULL,
  `ID_ATTRIBUT` INT(10) NOT NULL,
);