ALTER TABLE BESOIN_CLIENT ADD PRIMARY KEY (ID_BESOIN_CLIENT);

ALTER TABLE BESOIN_CLIENT ADD FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);

ALTER TABLE BESOIN_CLIENT ADD FOREIGN KEY (ID_TYPE_LINGE) REFERENCES TYPE_LINGE(ID_TYPE_LINGE);

ALTER TABLE BESOIN_CLIENT ADD FOREIGN KEY (ID_ADRESSE) REFERENCES ADRESSE(ID_ADRESSE);

ALTER TABLE BESOIN_CLIENT ADD FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT);