ALTER TABLE OFFRE ADD PRIMARY KEY (ID_OFFRE);

ALTER TABLE OFFRE ADD FOREIGN KEY (ID_SERVICE) REFERENCES SERVICES(ID_SERVICE);

ALTER TABLE OFFRE ADD FOREIGN KEY (ID_TYPE_LINGE) REFERENCES TYPE_LINGE(ID_TYPE_LINGE);