ALTER TABLE PRIVILEGE_UTILISATEUR ADD PRIMARY KEY (ID_PRIVILEGE, ID_UTILISATEUR);

ALTER TABLE PRIVILEGE_UTILISATEUR ADD FOREIGN KEY (ID_PRIVILEGE) REFERENCES PRIVILEGE (ID_PRIVILEGE);

ALTER TABLE PRIVILEGE_UTILISATEUR ADD FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);