ALTER TABLE PRIVILEGE ADD PRIMARY KEY (ID_PRIVILEGE);

ALTER TABLE PRIVILEGE ADD FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);

ALTER TABLE PRIVILEGE ADD FOREIGN KEY (ID_PRESSING) REFERENCES PRESSING(ID_PRESSING);