ALTER TABLE PRIVILEGE_ROLES ADD PRIMARY KEY (ID_PRIVILEGE, ID_ROLE);

ALTER TABLE PRIVILEGE_ROLES ADD FOREIGN KEY (ID_PRIVILEGE) REFERENCES PRIVILEGE (ID_PRIVILEGE);

ALTER TABLE PRIVILEGE_ROLES ADD FOREIGN KEY(ID_ROLE) REFERENCES ROLES(ID_ROLE);