ALTER TABLE PROMO ADD PRIMARY KEY (ID_PROMO);

ALTER TABLE PROMO ADD FOREIGN KEY (ID_TYPE_LINGE) REFERENCES TYPE_LINGE(ID_TYPE_LINGE);

ALTER TABLE PROMO ADD FOREIGN KEY (ID_SERVICE) REFERENCES SERVICES(ID_SERVICE);