ALTER TABLE ROLES ADD PRIMARY KEY (ID_ROLE);

ALTER TABLE ROLES ADD FOREIGN KEY (ID_PRESSING) REFERENCES PRESSING(ID_PRESSING);

ALTER TABLE ROLES ADD FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);