ALTER TABLE SERVICES ADD PRIMARY KEY (ID_SERVICE);

ALTER TABLE SERVICES ADD FOREIGN KEY (ID_PRESSING) REFERENCES PRESSING(ID_PRESSING);

ALTER TABLE SERVICES ADD FOREIGN KEY (ID_TYPE_SERVICE) REFERENCES TYPE_SERVICE(ID_TYPE_SERVICE);